<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Institution;
use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = Course::query()->pluck('id', 'name');
        $institutionsByCity = Institution::query()->pluck('id', 'city');

        $students = [
            [
                'course' => 'Curso básico',
                'name' => 'Juan',
                'last_name' => 'Pérez',
                'email' => 'alumno@agenda-maxpi.test',
                'phone' => '+52 55 1111 2222',
                'address' => 'Av. Universidad 100, Col. Del Valle',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '03100',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'María',
                'last_name' => 'González',
                'email' => 'maria.gonzalez@agenda-maxpi.test',
                'phone' => '+52 55 2222 3333',
                'address' => 'Calle Reforma 245',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '06600',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Alejandro',
                'last_name' => 'Hernández',
                'email' => 'alejandro.hernandez@agenda-maxpi.test',
                'phone' => '+52 33 1234 5678',
                'address' => 'Av. Chapultepec 890',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'zip' => '44160',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Fernanda',
                'last_name' => 'Ruiz',
                'email' => 'fernanda.ruiz@agenda-maxpi.test',
                'phone' => '+52 81 9876 5432',
                'address' => 'Av. Constitución 1200',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'zip' => '64000',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Diego',
                'last_name' => 'Morales',
                'email' => 'diego.morales@agenda-maxpi.test',
                'phone' => '+52 222 456 7890',
                'address' => 'Blvd. Atlixcáyotl 512',
                'city' => 'Puebla',
                'state' => 'Puebla',
                'zip' => '72810',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'Valentina',
                'last_name' => 'Castro',
                'email' => 'valentina.castro@agenda-maxpi.test',
                'phone' => '+52 55 3333 4444',
                'address' => 'Calz. de Tlalpan 1802',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '14000',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Santiago',
                'last_name' => 'Torres',
                'email' => 'santiago.torres@agenda-maxpi.test',
                'phone' => '+52 442 111 2233',
                'address' => 'Av. Pie de la Cuesta 702',
                'city' => 'Querétaro',
                'state' => 'Querétaro',
                'zip' => '76090',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Camila',
                'last_name' => 'Vargas',
                'email' => 'camila.vargas@agenda-maxpi.test',
                'phone' => '+52 55 4444 5555',
                'address' => 'Av. Insurgentes Sur 1458',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '03940',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'Luis Alberto',
                'last_name' => 'Sánchez',
                'email' => 'luis.sanchez@agenda-maxpi.test',
                'phone' => '+52 664 555 6677',
                'address' => 'Paseo de los Héroes 10234',
                'city' => 'Tijuana',
                'state' => 'Baja California',
                'zip' => '22010',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Ximena',
                'last_name' => 'López',
                'email' => 'ximena.lopez@agenda-maxpi.test',
                'phone' => '+52 55 5555 6666',
                'address' => 'Av. Revolución 1500',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '01020',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Roberto',
                'last_name' => 'Jiménez',
                'email' => 'roberto.jimenez@agenda-maxpi.test',
                'phone' => '+52 477 777 8899',
                'address' => 'Blvd. López Mateos 1501',
                'city' => 'León',
                'state' => 'Guanajuato',
                'zip' => '37270',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'Andrea',
                'last_name' => 'Flores',
                'email' => 'andrea.flores@agenda-maxpi.test',
                'phone' => '+52 55 6666 7777',
                'address' => 'Eje Central Lázaro Cárdenas 13',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '06000',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Miguel Ángel',
                'last_name' => 'Ríos',
                'email' => 'miguel.rios@agenda-maxpi.test',
                'phone' => '+52 998 888 9900',
                'address' => 'Av. Tulum 260',
                'city' => 'Cancún',
                'state' => 'Quintana Roo',
                'zip' => '77500',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Daniela',
                'last_name' => 'Ortiz',
                'email' => 'daniela.ortiz@agenda-maxpi.test',
                'phone' => '+52 55 7777 8888',
                'address' => 'Av. Patriotismo 229',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '03800',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'Jorge Eduardo',
                'last_name' => 'Navarro',
                'email' => 'jorge.navarro@agenda-maxpi.test',
                'phone' => '+52 614 321 6549',
                'address' => 'Av. Teófilo Borunda 8000',
                'city' => 'Chihuahua',
                'state' => 'Chihuahua',
                'zip' => '31125',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Paola',
                'last_name' => 'Mendoza',
                'email' => 'paola.mendoza@agenda-maxpi.test',
                'phone' => '+52 55 8888 9999',
                'address' => 'Av. Universidad 3000',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '04510',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Ricardo',
                'last_name' => 'Delgado',
                'email' => 'ricardo.delgado@agenda-maxpi.test',
                'phone' => '+52 33 8765 4321',
                'address' => 'Av. López Mateos Sur 2077',
                'city' => 'Guadalajara',
                'state' => 'Jalisco',
                'zip' => '44500',
            ],
            [
                'course' => 'Curso básico',
                'name' => 'Guadalupe',
                'last_name' => 'Reyes',
                'email' => 'guadalupe.reyes@agenda-maxpi.test',
                'phone' => '+52 55 9999 0000',
                'address' => 'Calz. Ignacio Zaragoza 550',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '09000',
            ],
            [
                'course' => 'Curso intermedio',
                'name' => 'Héctor Manuel',
                'last_name' => 'Aguilar',
                'email' => 'hector.aguilar@agenda-maxpi.test',
                'phone' => '+52 81 2345 6789',
                'address' => 'Av. Morones Prieto 3000',
                'city' => 'Monterrey',
                'state' => 'Nuevo León',
                'zip' => '64710',
            ],
            [
                'course' => 'Curso avanzado',
                'name' => 'Sofía',
                'last_name' => 'Ramírez',
                'email' => 'sofia.ramirez@agenda-maxpi.test',
                'phone' => '+52 55 1010 2020',
                'address' => 'Av. Ejército Nacional 769',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip' => '11520',
            ],
        ];

        foreach ($students as $data) {
            Student::query()->updateOrCreate(
                ['email' => $data['email']],
                [
                    'course_id' => $courses[$data['course']] ?? null,
                    'institution_id' => $institutionsByCity[$data['city']] ?? null,
                    'name' => $data['name'],
                    'last_name' => $data['last_name'],
                    'password' => 'password',
                    'phone' => $data['phone'],
                    'address' => $data['address'],
                    'city' => $data['city'],
                    'state' => $data['state'],
                    'zip' => $data['zip'],
                    'country' => 'México',
                ]
            );
        }
    }
}
